<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
=======
# Generated by Django 4.0.2 on 2022-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
>>>>>>> github/master
