# Generated by Django 4.0.2 on 2022-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='For',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project',
            field=models.TextField(max_length=500),
        ),
    ]
